export const types = {
  SET_USER_DATA: "SET_USER_DATA",
  OPEN_MODAL_WINDOW: "OPEN_MODAL_WINDOW",
  OPEN_LOGIN_DEFINITELY: "OPEN_LOGIN_DEFINITELY",
  SET_REMOVE: "SET_REMOVE",
  CHANGE_WINDOW: "CHANGE_WINDOW",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  SAVE_FILES: "SAVE_FILES",
  SAVE_MODEL_ID: "SAVE_MODEL_ID",
  TOGGLE_USER_INFO: "TOGGLE_USER_INFO",
  READY_FOR_SCREEN: "READY_FOR_SCREEN",
  LOG_OUT: "LOG_OUT"
};

