export const types = {
  SET_USER_DATA: "SET_USER_DATA",
  OPEN_MODAL_WINDOW: "OPEN_MODAL_WINDOW",
  OPEN_LOGIN_DEFINITELY: "OPEN_LOGIN_DEFINITELY",
  SET_REMOVE: "SET_REMOVE",
  CHANGE_WINDOW: "CHANGE_WINDOW",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE"
};

